services:
  - type: web
    name: instagram-reel-api
    env: node
    plan: free
    buildCommand: |
      cp package.json /opt/render/project/src/ && cd /opt/render/project/src && npm install
    startCommand: npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
    packages:
      - ffmpeg-static
