services:
  - type: web
    name: instagram-real-api
    env: node
    plan: free
    buildCommand: npm install && npm run build  # Modifié pour utiliser npm run build
    startCommand: npm start  # Modifié pour utiliser npm start
    nodeVersion: 18.0.0
    envVars:
      - key: NODE_ENV
        value: production
    rootDirectory: ./project  # Spécifié car vos fichiers sont dans le dossier project
