services:
  - type: web
    name: instagram-reel-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 18.0.0
    envVars:
      - key: NODE_ENV
        value: production
    packages:
      - ffmpeg
    rootDirectory: .
