services:
  - type: web
    name: instagram-real-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 18.0.0
    envVars:
      - key: NODE_ENV
        value: production
    rootDirectory: ./project  # Modifié pour pointer vers le dossier project
