services:
  - type: web
    name: instagram-reel-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    packages:
      - ffmpeg
    rootDirectory: .
