services:
  - type: web
    name: instagram-reel-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - package.json
        - api/**
    packages:
      - ffmpeg-static
