services:
  - type: web
    name: instagram-real-api
    env: node
    plan: free
    buildCommand: vite build  # Modifié car vous utilisez vite
    startCommand: node server.js  # Modifié selon votre package.json
    nodeVersion: 18.0.0
    envVars:
      - key: NODE_ENV
        value: production
    rootDirectory: ./  # Modifié pour pointer vers la racine
